trigger:
  branches:
    include:
      - main  # Trigger on commits to the 'main' branch

pool:
  name: 'Github_ReadyAPI_Pool1'  # Use your custom pool

steps:
  - checkout: self  # Checkout your code

  # Install Java (required for ReadyAPI CLI)
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'

  # Download and install ReadyAPI CLI
  - script: |
      echo "Downloading ReadyAPI CLI..."
      curl -o ReadyAPI-CLI.zip https://<download-link-from-smartbear>  # Replace with actual download link
      unzip ReadyAPI-CLI.zip -d ReadyAPI-CLI
    displayName: 'Install ReadyAPI CLI'

  # Run ReadyAPI tests using the XML project file
  - script: |
      echo "Running ReadyAPI tests..."
      ReadyAPI-CLI/bin/testrunner.bat -f ./test-results -R JUnitExport ./REST Project 1-readyapi-project.xml
    displayName: 'Run ReadyAPI Tests'

  # Publish test results (optional)
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'test-results/**/*.xml'
    condition: always()  # Publish even if tests fail
